AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: My Multimedia Manager application

Globals:
  Function:
    Runtime: java17
    MemorySize: 256
    Timeout: 29

Resources:
  MyMultimediaManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTION'"
        AllowOrigin: "'https://master.d5i6lke35o8tb.amplifyapp.com'"

  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      CodeUri: .
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyMultimediaManagerApi

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: "MyMultimediaManagerUserPool"
      AutoVerifiedAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
      EmailVerificationMessage: "Witaj {username},\n\nDziękujemy za rejestrację. Prosimy potwierdzić swój adres e-mail, klikając poniższy link:\n\n{####}\n\nDziękujemy."
      EmailVerificationSubject: "[my-multimedia-manager] Potwierdź swój adres e-mail"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          RequireLowercase: true
      UsernameAttributes:
        - email

  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: "MyMultimediaManagerUserPoolClient"
      UserPoolId: !Ref MyCognitoUserPool

  MyCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      Domain: "my-multimedia-manager"

Outputs:
  MyMultimediaManager:
    Description: API Gateway MyMultimediaManager Endpoint
    Value:
      Fn::Sub: https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/