AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: My Multimedia Manager application

Globals:
  Function:
    Runtime: java17
    MemorySize: 256
    Timeout: 29

Resources:
  MyMultimediaManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'*'"
        AllowOrigin: "'*'"

  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      CodeUri: .
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyMultimediaManagerApi

Outputs:
  MyMultimediaManager:
    Description: API Gateway MyMultimediaManager Endpoint
    Value:
      Fn::Sub: https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/