AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyMultimediaManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyMultimediaManagerApi
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyMultimediaManagerLambda
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Timeout: 30 # adjust as needed
      Events:
        MyMultimediaManagerApiEvent:
          Type: Api
          Properties:
            RestApiId:
              Fn::ImportValue: !Sub "${MyMultimediaManagerApi}-RestApiId"
            Path: /
            Method: ANY

Outputs:
  MyMultimediaManagerApiId:
    Description: "API Gateway ID"
    Value:
      Fn::ImportValue: !Sub "${MyMultimediaManagerApi}-RestApiId"
  MyMultimediaManagerApiUrl:
    Description: "API Gateway URL"
    Value:
      Fn::Sub: "https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
