AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyMultimediaManagerFunction
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Timeout: 30
      Events:
        MyMultimediaManagerApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY

Outputs:
  MyMultimediaManagerApiId:
    Description: "API Gateway ID"
    Value:
      Ref: MyMultimediaManagerApi
  MyMultimediaManagerApiUrl:
    Description: "API Gateway URL"
    Value:
      Fn::Sub: "https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
