AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  MyMultimediaManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: MyMultimediaManagerApi
      StageName: Prod
      Cors:
        AllowMethods: "'GET,POST,PUT,DELETE,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MyMultimediaManagerFunction
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      Runtime: java17
      CodeUri: .
      Timeout: 30
      Architectures:
        - x86_64
      MemorySize: 2048
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        MyMultimediaManagerApiEvent:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: MyMultimediaManagerApi

Outputs:
  MyMultimediaManagerApiId:
    Description: "API Gateway ID"
    Value:
      Ref: MyMultimediaManagerApi
  MyMultimediaManagerApiUrl:
    Description: "API Gateway URL"
    Value:
      Fn::Sub: "https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
