AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: My Multimedia Manager application

Globals:
  Function:
    Runtime: java21
    MemorySize: 256
    Timeout: 900
  Api:
    TimeoutInMillis: 60000

Resources:
  MyMultimediaManagerApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn
        AddDefaultAuthorizerToCorsPreflight: False
      Cors:
        AllowHeaders: "'*'"
        AllowMethods: "'GET,POST,PUT,DELETE,OPTION'"
        AllowOrigin: "'https://www.my-multimedia-manager.com'"

  MyMultimediaManagerLambdaRoleTemplate:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: MyMultimediaManagerLambdaRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: DynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                Resource: '*'
        - PolicyName: SecretsManagerPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: '*'
        - PolicyName: CloudWatchLogsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: '*'

  MyMultimediaManagerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt MyMultimediaManagerLambdaRoleTemplate.Arn
      Handler: wrzesniak.rafal.my.multimedia.manager.aws.StreamLambdaHandler::handleRequest
      CodeUri: .
      AutoPublishAlias: live
      SnapStart:
        ApplyOn: PublishedVersions
      Environment:
        Variables:
          SPRING_PROFILES_ACTIVE: prod
      Events:
        ApiEvents:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId: !Ref MyMultimediaManagerApi

  MyCognitoUserPool:
    Type: AWS::Cognito::UserPool
    DeletionPolicy: Retain
    Properties:
      UserPoolName: "MyMultimediaManagerUserPool"
      DeletionProtection: 'ACTIVE'
      AutoVerifiedAttributes:
        - email
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_LINK
        EmailMessageByLink: "Cześć,<br/><br/>Dzięki za rejestrację. Proszę potwierdź swój adres e-mail, klikając poniższy link:<br/>{##Zweryfikuj konto##}<br/><br/>Dziękujemy."
        EmailSubjectByLink: "[my-multimedia-manager] Potwierdź swój adres e-mail"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireNumbers: true
          RequireSymbols: true
          RequireUppercase: true
          RequireLowercase: true
      UsernameAttributes:
        - email

  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    DeletionPolicy: Retain
    Properties:
      ClientName: "MyMultimediaManagerUserPoolClient"
      UserPoolId: !Ref MyCognitoUserPool

  MyCognitoUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    DeletionPolicy: Retain
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      Domain: "my-multimedia-manager"

### DynamoDB ###
## PROD ##
# Common tables
  UsersTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_Users'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ContentListsTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_ContentLists'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'listId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'listId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

# Product tables
  # Books
  BooksTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_Books'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'lubimyCzytacUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'lubimyCzytacUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  BookUserDetailsTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_BookUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'bookId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'bookId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Movies
  MoviesTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_Movies'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'filmwebUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'filmwebUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MovieUserDetailsTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_MovieUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'movieId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'movieId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Games
  GamesTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_Games'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'gryOnlineUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'gryOnlineUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  GameUserDetailsTableProd:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_prod_GameUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'gameId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'gameId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true


  ## DEV ##
  # Common tables
  UsersTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_Users'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  ContentListsTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_ContentLists'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'listId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'listId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Product tables
  # Books
  BooksTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_Books'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'lubimyCzytacUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'lubimyCzytacUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  BookUserDetailsTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_BookUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'bookId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'bookId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Movies
  MoviesTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_Movies'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'filmwebUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'filmwebUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  MovieUserDetailsTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_MovieUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'movieId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'movieId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  # Games
  GamesTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_Games'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'gryOnlineUrl'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'gryOnlineUrl'
          KeyType: 'HASH'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  GameUserDetailsTableDev:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: 'mmm_dev_GameUserDetails'
      DeletionProtectionEnabled: true
      AttributeDefinitions:
        - AttributeName: 'username'
          AttributeType: 'S'
        - AttributeName: 'gameId'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'username'
          KeyType: 'HASH'
        - AttributeName: 'gameId'
          KeyType: 'RANGE'
      BillingMode: PAY_PER_REQUEST
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

Outputs:
  MyMultimediaManager:
    Description: API Gateway MyMultimediaManager Endpoint
    Value:
      Fn::Sub: https://${MyMultimediaManagerApi}.execute-api.${AWS::Region}.amazonaws.com/prod/