spring:
  name: my-multimedia-manager
  main:
    allow-bean-definition-overriding: true

application:
  imdb:
    url: https://imdb-api.com/API
    url-pl: https://imdb-api.com/pl/API
    api-key: secret
    not-found: Server busy
    image-size: 384x528
    wikipedia: Wikipedia
    api:
      actor: Name
      movie: Title
      search: SearchMovie
      resize: ResizeImage

  filmweb:
    link:
      url: https://www.filmweb.pl
      prefix:
        movie: /film/
        actor: /person/
    search: search?q=

  lubimy-czytac:
    default-description: Ta książka nie ma opisu..
    unknown-publisher: Nieznany wydawca
    parsing:
      main-attribute: type
      main-attribute-value: application/ld+json
      href: href
      title: title
      publisher: wydawnictwo
      id: id
      description: book-description
      series: /cykl/
      original-release: Data pierwszego wydania oryginalnego

dynamodb:
  table:
    users: mmm_${spring.profiles.active}_Users
    content-lists: mmm_${spring.profiles.active}_ContentLists
    books: mmm_${spring.profiles.active}_Books
    book-user-details: mmm_${spring.profiles.active}_BookUserDetails
    movies: mmm_${spring.profiles.active}_Movies
    movie-user-details: mmm_${spring.profiles.active}_MovieUserDetails
    games: mmm_${spring.profiles.active}_Games
    game-user-details: mmm_${spring.profiles.active}_GameUserDetails

server:
  servlet:
    session:
      tracking-modes: COOKIE
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG