spring:
  name: my-multimedia-manager
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: none
                create-target: V0__schema.sql

application:
  imdb:
    url: https://imdb-api.com/API
    url-pl: https://imdb-api.com/pl/API
    api-key: secret
    not-found: Server busy
    image-size: 384x528
    api:
      actor: Name
      movie: Title
      search: SearchMovie
      resize: ResizeImage

  filmweb:
    link:
      url: https://www.filmweb.pl
      prefix:
        movie: /film/
        actor: /person/
    search: search?q=

  jwt:
    secret: asdsalqrk1232115dfas@!#!@sds
    expirationTime: 3600000

server:
  error:
    include-message: always
    include-stacktrace: never