spring:
  name: my-multimedia-manager
  main:
    allow-bean-definition-overriding: true

application:
  imdb:
    url: https://imdb-api.com/API
    url-pl: https://imdb-api.com/pl/API
    api-key: secret
    not-found: Server busy
    image-size: 384x528
    wikipedia: Wikipedia
    api:
      actor: Name
      movie: Title
      search: SearchMovie
      resize: ResizeImage

  filmweb:
    link:
      url: https://www.filmweb.pl
      prefix:
        movie: /film/
        actor: /person/
    search: search?q=

  lubimy-czytac:
    default-descritption: Ta książka nie ma opisu..
    unknown-publisher: Nieznany wydawca
    parsing:
      main-attribute: type
      main-attribute-value: application/ld+json
      href: href
      publisher: wydawnictwo
      id: id
      description: book-description
      series: /cykl/

server:
  servlet:
    session:
      tracking-modes: COOKIE
  error:
    include-message: always
    include-stacktrace: never

logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonsRequestLoggingFilter: DEBUG