spring:
  name: my-multimedia-manager
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: create
                create-target: V2__schema.sql
