spring:
  name: my-multimedia-manager
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
        hibernate:
          default_schema: MULTIMEDIA
        javax:
          persistence:
            schema-generation:
              create-source: metadata
              scripts:
                action: none
                create-target: V0__schema.sql

application:
  imdb:
    url: https://imdb-api.com/API
    url-pl: https://imdb-api.com/pl/API
    api-key: secret
    not-found: Server busy
    image-size: 384x528
    wikipedia: Wikipedia
    api:
      actor: Name
      movie: Title
      search: SearchMovie
      resize: ResizeImage

  filmweb:
    link:
      url: https://www.filmweb.pl
      prefix:
        movie: /film/
        actor: /person/
    search: search?q=

  lubimy-czytac:
    default-descritption: Ta książka nie ma opisu..
    unknown-publisher: Nieznany wydawca
    parsing:
      main-attribute: type
      main-attribute-value: application/ld+json
      href: href
      publisher: wydawnictwo
      id: id
      description: book-description

  jwt:
    secret: secret
    expirationTime: 3600000

server:
  error:
    include-message: always
    include-stacktrace: never

aws:
  access-key: secret
  secret-key: secret
  s3-bucket-name: multimedia-images