create table game (id bigint generated by default as identity, created_on date, description varchar(1024), gry_online_url varchar(255), publisher varchar(255), rating_count integer, rating_value decimal(19,2), release_date date, studio varchar(255), title varchar(255), primary key (id));
create table game_game_platform (game_id bigint not null, game_platform varchar(255));
create table game_genre_list (game_id bigint not null, genre_list varchar(255));
create table game_play_modes (game_id bigint not null, play_modes varchar(255));
create table game_content_list (id bigint generated by default as identity, content_list_type varchar(255), is_all_content_list boolean not null, name varchar(255), primary key (id));
create table game_content_list_content_list (game_content_list_id bigint not null, content_list_id bigint not null);
create table game_user_details (game_id bigint not null, user_id bigint not null, finished_on date, game_platform varchar(50), primary key (game_id, user_id));

create table users_game_lists (user_id bigint not null, game_lists_id bigint not null);
alter table users_game_lists add constraint UK_s7v88kjv1vcvsa4ruej0ao6xn unique (game_lists_id);
alter table game_game_platform add constraint FKk7e510wluky27ujnaidt4f3ld foreign key (game_id) references game;
alter table game_genre_list add constraint FK9o51ksekjjni8w8elcgd2sl5h foreign key (game_id) references game;
alter table game_play_modes add constraint FK1ibfqlp61nonjlm31451rsyy3 foreign key (game_id) references game;
alter table game_content_list_content_list add constraint FKki8k3ki3e7l4ftno3s9fdstkl foreign key (content_list_id) references game ON DELETE CASCADE;
alter table game_content_list_content_list add constraint FKn2kueqn6eh3lq4aeveje9k8g8 foreign key (game_content_list_id) references game_content_list;
alter table users_game_lists add constraint FKm5ye8rrmxbl43i1sjbdfilqj9 foreign key (game_lists_id) references game_content_list;
alter table users_game_lists add constraint FK3ywwskq17hixtjhurtrlm3oxy foreign key (user_id) references users;